//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.KSYS.Scheduler.JOBLINKsOperationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JOBLINKsModel", Namespace="http://schemas.datacontract.org/2004/07/Kerry.KSYS.Service.Models")]
    [System.SerializableAttribute()]
    public partial class JOBLINKsModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SourceUnidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UnidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SourceUnid {
            get {
                return this.SourceUnidField;
            }
            set {
                if ((this.SourceUnidField.Equals(value) != true)) {
                    this.SourceUnidField = value;
                    this.RaisePropertyChanged("SourceUnid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Unid {
            get {
                return this.UnidField;
            }
            set {
                if ((this.UnidField.Equals(value) != true)) {
                    this.UnidField = value;
                    this.RaisePropertyChanged("Unid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JOBLINKsOperationService.IJOBLINKsOperation")]
    public interface IJOBLINKsOperation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJOBLINKsOperation/AddByModel", ReplyAction="http://tempuri.org/IJOBLINKsOperation/AddByModelResponse")]
        int AddByModel(Kerry.KSYS.Scheduler.JOBLINKsOperationService.JOBLINKsModel[] models);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJOBLINKsOperation/AddByModel", ReplyAction="http://tempuri.org/IJOBLINKsOperation/AddByModelResponse")]
        System.Threading.Tasks.Task<int> AddByModelAsync(Kerry.KSYS.Scheduler.JOBLINKsOperationService.JOBLINKsModel[] models);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJOBLINKsOperation/Supplyment", ReplyAction="http://tempuri.org/IJOBLINKsOperation/SupplymentResponse")]
        int Supplyment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJOBLINKsOperation/Supplyment", ReplyAction="http://tempuri.org/IJOBLINKsOperation/SupplymentResponse")]
        System.Threading.Tasks.Task<int> SupplymentAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJOBLINKsOperationChannel : Kerry.KSYS.Scheduler.JOBLINKsOperationService.IJOBLINKsOperation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JOBLINKsOperationClient : System.ServiceModel.ClientBase<Kerry.KSYS.Scheduler.JOBLINKsOperationService.IJOBLINKsOperation>, Kerry.KSYS.Scheduler.JOBLINKsOperationService.IJOBLINKsOperation {
        
        public JOBLINKsOperationClient() {
        }
        
        public JOBLINKsOperationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JOBLINKsOperationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JOBLINKsOperationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JOBLINKsOperationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddByModel(Kerry.KSYS.Scheduler.JOBLINKsOperationService.JOBLINKsModel[] models) {
            return base.Channel.AddByModel(models);
        }
        
        public System.Threading.Tasks.Task<int> AddByModelAsync(Kerry.KSYS.Scheduler.JOBLINKsOperationService.JOBLINKsModel[] models) {
            return base.Channel.AddByModelAsync(models);
        }
        
        public int Supplyment() {
            return base.Channel.Supplyment();
        }
        
        public System.Threading.Tasks.Task<int> SupplymentAsync() {
            return base.Channel.SupplymentAsync();
        }
    }
}
