//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.KSYS.Scheduler.Test.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IJOBOperation")]
    public interface IJOBOperation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJOBOperation/AddCONSOLUNID", ReplyAction="http://tempuri.org/IJOBOperation/AddCONSOLUNIDResponse")]
        int AddCONSOLUNID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJOBOperation/AddCONSOLUNID", ReplyAction="http://tempuri.org/IJOBOperation/AddCONSOLUNIDResponse")]
        System.Threading.Tasks.Task<int> AddCONSOLUNIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJOBOperation/UpdateCONSOLUNID", ReplyAction="http://tempuri.org/IJOBOperation/UpdateCONSOLUNIDResponse")]
        int UpdateCONSOLUNID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJOBOperation/UpdateCONSOLUNID", ReplyAction="http://tempuri.org/IJOBOperation/UpdateCONSOLUNIDResponse")]
        System.Threading.Tasks.Task<int> UpdateCONSOLUNIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJOBOperation/RemoveCONSOLUNID", ReplyAction="http://tempuri.org/IJOBOperation/RemoveCONSOLUNIDResponse")]
        int RemoveCONSOLUNID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJOBOperation/RemoveCONSOLUNID", ReplyAction="http://tempuri.org/IJOBOperation/RemoveCONSOLUNIDResponse")]
        System.Threading.Tasks.Task<int> RemoveCONSOLUNIDAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJOBOperationChannel : Kerry.KSYS.Scheduler.Test.ServiceReference1.IJOBOperation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JOBOperationClient : System.ServiceModel.ClientBase<Kerry.KSYS.Scheduler.Test.ServiceReference1.IJOBOperation>, Kerry.KSYS.Scheduler.Test.ServiceReference1.IJOBOperation {
        
        public JOBOperationClient() {
        }
        
        public JOBOperationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JOBOperationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JOBOperationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JOBOperationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddCONSOLUNID() {
            return base.Channel.AddCONSOLUNID();
        }
        
        public System.Threading.Tasks.Task<int> AddCONSOLUNIDAsync() {
            return base.Channel.AddCONSOLUNIDAsync();
        }
        
        public int UpdateCONSOLUNID() {
            return base.Channel.UpdateCONSOLUNID();
        }
        
        public System.Threading.Tasks.Task<int> UpdateCONSOLUNIDAsync() {
            return base.Channel.UpdateCONSOLUNIDAsync();
        }
        
        public int RemoveCONSOLUNID() {
            return base.Channel.RemoveCONSOLUNID();
        }
        
        public System.Threading.Tasks.Task<int> RemoveCONSOLUNIDAsync() {
            return base.Channel.RemoveCONSOLUNIDAsync();
        }
    }
}
